config/routes.rb
Rails.application.routes.draw do
  get 'contact_forms/new'
  get 'contact_forms/create'
  root to: "pages#home"
  
  ############# DEVISE ############
  devise_for :users
  #################################
  ############# ADMIN #############
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  ############ BLAZER #############
  # authenticate :user, ->(user) { user.admin? } do  ##### PAS SÛR DE LE METTRE #####
  #   mount Blazer::Engine, at: "blazer"
  # end
  #################################
  ############ CONTACT ############
  resources :contact_forms, only: [:new, :create]
  #################################
  ############# USER ##############
  resources :users, only: [:show, :edit, :update] do
    get 'my_events', on: :member
  end
  #################################
  ######### ORGANIZATION ##########
  resources :organizations do
    resources :events do
      resources :articles, only: [:new, :create]
    end
    member do
      post 'create_event', to: 'organizations#create_event'
    #   post 'follow'           #### FOLLOW EN COURS ####
    #   delete 'unfollow'
    end  
  end
  #################################
  ############ EVENT ##############
  resources :events, except: [:destroy] do
    resources :participations, only: [:destroy]
  end
  resources :participations, only: [:create]
  #################################
  ########### CHATROOM ############
  # resources :chatrooms, only: [:show, :index] do
  #   resources :messages, only: :create
  #   collection do
  #     get :new_private_conversation
  #     post :create_private_conversation
  #   end
  # end
  # get 'chatrooms/:id/chatroom_partial', to: 'chatrooms#chatroom_partial', as: 'chatroom_partial'
  #################################
end

app/models/user.rb
class User < ApplicationRecord
  ########## RATACHEMENT ENTRE LES TABLES ##########
  # has_many :messages, dependent: :destroy
  has_many :directors, dependent: :destroy
  has_many :organizations, through: :directors
  has_many :participations, dependent: :destroy
  has_many :events, through: :participations
  has_many :participating_events, through: :participations, source: :event
  ##################################################

  ############ VALIDATION ############
  has_one_attached :avatar
  validates :nickname, presence: true, format: { without: /\s/ }
  ####################################

  ########## VÉRIFICATION ##########
  def director?
    directors.exists?(user: self)
  end
  ##################################

  ############# DEVISE #############
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  ##################################
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :user, only: [:show, :edit, :update, :update_avatar, :my_events]

    def show
      authorize @user
      @participations = Participation.where(user_id: @user.id).includes(:event)
      @participations_by_date = @participations.group_by { |p| p.event.start_time.to_date }
      # @followed_organizations = @user.following
    end

    def edit
      authorize @user
    end

    def update
        if @user.update(user_params)
        redirect_to user_path, notice: 'Profil mis à jour avec succès.'
        else
        render :edit
        end
        authorize @user
    end

    def update_avatar
        if @user.update(user_avatar_params)
        redirect_to user_path, notice: 'Photo de profil mise à jour avec succès.'
        else
        render :show
        end
    end

    def my_events
      authorize @user
      @participating_events = @user.events
    end

    private

    def user
      @user = current_user
    end
  
    def user_avatar_params
      params.require(:user).permit(:avatar)
    end
    
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :avatar, :nickname)
    end
end

app/views/users/edit.html.erb
<%= form_for(@user, url: user_path(@user), method: :patch, html: { multipart: true }) do |f| %>
  <%= f.label :nickname %>
  <%= f.text_field :nickname %>

  <%= f.label :avatar %>
  <%= f.file_field :avatar %>

  <%= f.submit "Mettre à jour le profil" %>
<% end %>

<%= link_to "Retour", :back %>

app/views/users/my_events.html.erb
<div class="container">
    <h1 class="pt-3">Événements auxquels je participe</h1>
    <div class="row align-items-center">
        <% @participating_events.each do |event| %>
            <div class="col-xl-4 col-md-6 pb-4">
                <div class="card card-ac">
                    <div class="photo-taille">
                        <img src="<%= rails_blob_path event.picture %>" alt="Événement" class="object-fit-cover img-fluid">
                    </div>
                    <div class="card-body">
                        <p class="date-start">Le <%= event.start_time.strftime('%d %m %y') %><p>
                        <h3 class="card-title titre-carte"><%= event.title %></h3>

                    </div>
                        <p class="para-card"><%= event.address %> </p>
                    <div class="card-bottom">
                        <a class="bouton-ac" onclick="window.location.href='<%= event_path(event) %>'">Voir les articles <i class="fa fa-arrow-right"></i></a>
                    </div>
                </div>
            </div>
        <% end %>

    </div>
</div>

app/views/users/show.html.erb
<div class="container ">
  <div class='prev-wrap pt-3'>
    <%= link_to :back do %>
      <div class="btn-test"><i class="fa fa-angle-left"></i> Précédent </div>
    <% end %>
  </div>
  <section class="section-profil px-2">
    <div class="profil-page">
      <% if current_user.avatar.present? %>
          <%= image_tag rails_blob_path(current_user.avatar), alt: "Avatar de #{current_user.email}", class: "profil-avatar" %>
      <% else %>
      <%= image_tag "cover.png", width: 100, height: 100, alt: "Avatar par défaut", class: "profil-avatar" %>
      <% end %>
    </div>
    <div class="case-profil ps-5">
      <div class="px-2 pt-1">
        <h2><%= current_user.nickname %></h2>
      </div>
      <div class="case-menu">
        <div class="px-2 pt-2">
          <%= link_to "Modifier profil", edit_user_path(current_user), method: :get, class: "bouton-profil" %>
        </div> 
        <div class="px-2 pt-2">
          <%= link_to "Mes évènements", my_events_user_path(current_user), method: :get, class: "bouton-profil" %>
        </div>
      </div>
    </div>
    <div class="px-2 pt-2">
      <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "bouton-deco bi bi-x-square" %>
    </div>
  </section>

  <h2>Mon calendrier</h2>
  <div class="pb-5">
    <%= month_calendar(events: @participations) do |date, participations_of_date| %>
      <%= date %>
        <% participations_of_date.each do |participation| %>
          <button class="meeting phone-view truncated-title">
            <%= link_to participation.event.title.truncate(1, omission: ''), event_path(participation.event) %>
          </button>
          <button class="meeting desktop-view">
            <%= link_to participation.event.title, event_path(participation.event), class: 'participation-calendar' %>
          </button>
        <% end %>
    <% end %>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>