config/routes.rb
Rails.application.routes.draw do
  get 'contact_forms/new'
  get 'contact_forms/create'
  root to: "pages#home"
  
  ############# DEVISE ############
  devise_for :users
  #################################
  ############# ADMIN #############
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  ############ BLAZER #############
  # authenticate :user, ->(user) { user.admin? } do  ##### PAS SÛR DE LE METTRE #####
  #   mount Blazer::Engine, at: "blazer"
  # end
  #################################
  ############ CONTACT ############
  resources :contact_forms, only: [:new, :create]
  #################################
  ############# USER ##############
  resources :users, only: [:show, :edit, :update] do
    get 'my_events', on: :member
  end
  #################################
  ######### ORGANIZATION ##########
  resources :organizations do
    resources :events do
      resources :articles, only: [:new, :create]
    end
    member do
      post 'create_event', to: 'organizations#create_event'
    #   post 'follow'           #### FOLLOW EN COURS ####
    #   delete 'unfollow'
    end  
  end
  #################################
  ############ EVENT ##############
  resources :events, except: [:destroy] do
    resources :participations, only: [:destroy]
  end
  resources :participations, only: [:create]
  #################################
  ########### CHATROOM ############
  # resources :chatrooms, only: [:show, :index] do
  #   resources :messages, only: :create
  #   collection do
  #     get :new_private_conversation
  #     post :create_private_conversation
  #   end
  # end
  # get 'chatrooms/:id/chatroom_partial', to: 'chatrooms#chatroom_partial', as: 'chatroom_partial'
  #################################
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="border-top">
    <a href="#" class="btn scroll-laptop" data-controller="scroll">
        <span class="" data-scroll-target="scroll" data-action="scroll@window->scroll#updateScroll">
            <i class="fa-sharp fa-solid fa-caret-up fa-bounce fa-xs" style="color: #21ff9d;"></i>
        </span>
    </a>

    <div class="container text-center pb-2">
        <div class="row">
            <%# <div class='footer-top'>
                <div class='col footer-col'>
                    <h3>Menu</h3>
                    <a href="#">Accueil</a>
                    <a href="#">Associations</a>
                    <a href="#">Évènements</a>
                    <a href="#">Profil</a>
                </div>
                <div class='col footer-col'>
                    <h3>Menu</h3>
                    <a href="#">Accueil</a>
                    <a href="#">Associations</a>
                    <a href="#">Évènements</a>
                    <a href="#">Profil</a>
                </div>
            </div> %>
            <div class="col footer-middle pt-2">
                <h3>Restez à jour</h3>
                <form>
                    <label for="newsletter">Inscrivez-vous à la newsletter pour recevoir les dernières informations.</label>
                    <div>
                        <input type="email" name="newsletter" id="newsletter" placeholder="exemple@gmail.com" required>
                        <input type="submit" value="Inscription">
                    </div>
                </form>
            </div>
            <div class="col footer-bottom mt-2">
                <a href="https://facebook.com" target="_blank" class="social"><i class="fa-brands fa-facebook"></i></a>
                <a href="https://linkedin.com" target="_blank" class="social"><i class="fa-brands fa-linkedin"></i></a>
                <a href="https://twitter.com" target="_blank" class="social"><i class="fa-brands fa-square-twitter"></i></a>
            </div>
            <div class="copyright-text text-center" data-controller="current-year">
                <p>Copyright&nbsp;&copy;&nbsp;<a href="//www.dannacode.com" target="_blank">DannaCode</a>&nbsp;<span data-current-year-target="year"></span>.&nbsp;Tous droits réservés.</p>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid text-white">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "cover.png" %>
      PosiLink
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Accueil", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Associations", organizations_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Événements", my_events_user_path(current_user), class: "nav-link" %>
          </li>
          <!-- AVATAR PROFIL-->
          <li class="nav-item dropdown avat-pic">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.avatar.present? %>
                <%= image_tag rails_blob_path(current_user.avatar), class: 'avatar', alt: "Avatar de #{current_user.nickname}" %>
              <% else %>
                <%= image_tag "cover.png", alt: "Avatar par défaut", class: "avatar" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profil", user_path(current_user), class: "dropdown-item" %>
              <%# <%= link_to "Messages", chatrooms_path, class: "dropdown-item" %>
              <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <!-- END -->
        <% else %>
          <li class="nav-item">
            <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Inscription", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_phone_footer.html.erb
<div class="mode-phone pb-3"></div>
<div class="bouton-phone" data-controller="button-phone">
    <a href="/"><i class="fa-solid fa-house" data-button-phone-target="icon"></i></a>
    <a href="/organizations"><i class="fa-solid fa-earth-americas" data-button-phone-target="icon"></i></a>
    <% if user_signed_in? %>
        <%= link_to my_events_user_path(current_user) do %>
            <i class="fa-solid fa-handshake-angle" data-button-phone-target="icon"></i>
        <% end %>
    <% else %>
        <%= link_to new_user_session_path do %>
            <i class="fa-solid fa-handshake-angle"></i>
        <% end %>
    <% end %>
    <% if user_signed_in? %>
        <%# <%= link_to chatrooms_path do %>
            <%# <i class="fa-solid fa-paper-plane" data-button-phone-target="icon"></i> %>
        <%# <% end %>
    <% else %>
        <%= link_to new_user_session_path do %>
            <i class="fa-solid fa-paper-plane"></i>
        <% end %>
    <% end %>
    <% if user_signed_in? %>
        <% if current_user.avatar.present? %>
            <%= link_to user_path(current_user), class:'avatar' do %>
                <%= image_tag rails_blob_path(current_user.avatar), class: 'avatar', alt: "Avatar de #{current_user.nickname}" %> 
            <% end %>
        <% else %>
            <%= link_to user_path(current_user), class:'avatar' do %>
                <%= image_tag "cover.png", alt: "Avatar par défaut", class: "avatar" %>
            <% end %>
        <% end %>
    <% else %>
        <%= link_to new_user_session_path do %>
            <i class="fa-solid fa-user borger-end"></i>
        <% end %>
    <% end %>
</div>

app/views/shared/_photo_card.html.erb
<img src="<%= cl_image_path event.photo.key %>" alt="Image de la carte">
<p><%= event.start_time.strftime("%d-%m-%Y") %></p>
<%= link_to event.title, organization_event_path(event.organization, event), class: "button" %>