config/routes.rb
Rails.application.routes.draw do
  get 'contact_forms/new'
  get 'contact_forms/create'
  root to: "pages#home"
  
  ############# DEVISE ############
  devise_for :users
  #################################
  ############# ADMIN #############
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  ############ BLAZER #############
  # authenticate :user, ->(user) { user.admin? } do  ##### PAS SÛR DE LE METTRE #####
  #   mount Blazer::Engine, at: "blazer"
  # end
  #################################
  ############ CONTACT ############
  resources :contact_forms, only: [:new, :create]
  #################################
  ############# USER ##############
  resources :users, only: [:show, :edit, :update] do
    get 'my_events', on: :member
  end
  #################################
  ######### ORGANIZATION ##########
  resources :organizations do
    resources :events do
      resources :articles, only: [:new, :create]
    end
    member do
      post 'create_event', to: 'organizations#create_event'
    #   post 'follow'           #### FOLLOW EN COURS ####
    #   delete 'unfollow'
    end  
  end
  #################################
  ############ EVENT ##############
  resources :events, except: [:destroy] do
    resources :participations, only: [:destroy]
  end
  resources :participations, only: [:create]
  #################################
  ########### CHATROOM ############
  # resources :chatrooms, only: [:show, :index] do
  #   resources :messages, only: :create
  #   collection do
  #     get :new_private_conversation
  #     post :create_private_conversation
  #   end
  # end
  # get 'chatrooms/:id/chatroom_partial', to: 'chatrooms#chatroom_partial', as: 'chatroom_partial'
  #################################
end

app/views/pages/home.html.erb
<% content_for :meta_title, "La communauté • Posilink" %>
<% content_for :meta_description, "Les bonnes actions" %>

<div class="banner border-bottom border-white">
  <div class="container">
    <h1>Les associations contribuent à notre bien-être à tous !</h1>
    <p>Aidez-nous à améliorer vôtre communauté.</p>
  </div>
</div>
<div class="container mt-3 mb-5">
    <div class="row">
        <div class="col home-style">
          <% if user_signed_in? %>
            <h2 class="mt-3">Bon retour parmi nous <span class="phrase-couleur"><%= current_user.nickname %></span> !</h2>
            <% if current_user.admin %>
              <br>
              <div class="d-flex mt-5">
                <%= link_to "/admin", class:"button" do %>
                  <div class="button__line"></div>
                  <div class="button__line"></div>
                  <span class="button__text">DASHBOARD ADMIN</span>
                  <div class="button__drow1"></div>
                  <div class="button__drow2"></div>
                <% end %>
              </div>
            <% elsif current_user.director? %>
              <div class="d-flex mt-5">
                <%= link_to edit_organization_path(@organization), class:"button" do %>
                  <div class="button__line"></div>
                  <div class="button__line"></div>
                  <span class="button__text">MON ASSOCIATION</span>
                  <div class="button__drow1"></div>
                  <div class="button__drow2"></div>
                <% end %>
              </div>
            <% else %>
              <div class="d-flex mt-5">
                <%= link_to organizations_path, class:"button" do %>
                  <div class="button__line"></div>
                  <div class="button__line"></div>
                  <span class="button__text">LES ASSOCIATIONS</span>
                  <div class="button__drow1"></div>
                  <div class="button__drow2"></div>
                <% end %>
              </div>
              <div class="mt-3">
                <h4>Vous êtes une association ?</h4>
                <%= link_to contact_forms_new_path, class: "button ml-3" do %>
                  <div class="button__line"></div>
                  <div class="button__line"></div>
                  <span class="button__text">NOUS CONTACTER</span>
                  <div class="button__drow1"></div>
                  <div class="button__drow2"></div>
                <% end %>
              </div>
            <% end %>
          <% else %>
            <h2>REJOIGNEZ <span class="phrase-couleur">POSILINK</span></h2>
            <br>
            <h3 class="bold-h3">Où les <span class="phrase-couleur">bonnes actions</span> créent des liens qui inspirent. Devenez un moteur de positivité et partagez votre impact. <br>Ensemble, faisons du bien et construisons un <span class="phrase-couleur">avenir solidaire</span> !</h3>
            <br>
            <div class="d-flex">
              <%= link_to new_user_registration_path, class:"button" do %>
                <div class="button__line"></div>
                <div class="button__line"></div>
                <span class="button__text">NOUS REJOINDRE</span>
                <div class="button__drow1"></div>
                <div class="button__drow2"></div>
              <% end %>
            </div>
          <% end %>
        </div>
    </div>
</div>