config/routes.rb
Rails.application.routes.draw do
  get 'contact_forms/new'
  get 'contact_forms/create'
  root to: "pages#home"
  
  ############# DEVISE ############
  devise_for :users
  #################################
  ############# ADMIN #############
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  ############ BLAZER #############
  # authenticate :user, ->(user) { user.admin? } do  ##### PAS SÛR DE LE METTRE #####
  #   mount Blazer::Engine, at: "blazer"
  # end
  #################################
  ############ CONTACT ############
  resources :contact_forms, only: [:new, :create]
  #################################
  ############# USER ##############
  resources :users, only: [:show, :edit, :update] do
    get 'my_events', on: :member
  end
  #################################
  ######### ORGANIZATION ##########
  resources :organizations do
    resources :events do
      resources :articles, only: [:new, :create]
    end
    member do
      post 'create_event', to: 'organizations#create_event'
    #   post 'follow'           #### FOLLOW EN COURS ####
    #   delete 'unfollow'
    end  
  end
  #################################
  ############ EVENT ##############
  resources :events, except: [:destroy] do
    resources :participations, only: [:destroy]
  end
  resources :participations, only: [:create]
  #################################
  ########### CHATROOM ############
  # resources :chatrooms, only: [:show, :index] do
  #   resources :messages, only: :create
  #   collection do
  #     get :new_private_conversation
  #     post :create_private_conversation
  #   end
  # end
  # get 'chatrooms/:id/chatroom_partial', to: 'chatrooms#chatroom_partial', as: 'chatroom_partial'
  #################################
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :directors, dependent: :destroy
  has_many :users, through: :directors
  has_many :events, dependent: :destroy
  has_one_attached :avatar

  enum category: {
    ecologie: "écologie",
    culture: "culture",
    sport: "sport",
    sante: "santé",
    education: "éducation",
    humanitaire: "humanitaire"
  }
  validates :category, inclusion: { in: categories.keys, message: "Catégorie invalide" }
  

  include PgSearch::Model
  pg_search_scope :search_by_organization,
                  against: [:name, :category, :description],
                  using: {
                      tsearch: { prefix: true }
                  }

  def category_form_value
    self.class.categories.key(category) || category
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  
  def index
      if params[:query].present?
          @organizations = Organization.search_by_organization(params[:query])
      else
          @organizations = Organization.all
      end
      params[:query] = ""
      if user_signed_in? && current_user.director?
        @organization = current_user.organizations.first
      end
      @filtered_organizations = policy_scope(Organization)
  end

  def show
      @organization = Organization.find(params[:id])
      @events = @organization.events
      @markers = @events.geocoded.map do |event|
        {
          lat: event.latitude,
          lng: event.longitude,
          info_window_html: render_to_string(partial: "info_window", locals: {event: event})
        }
      end
      authorize @organization
  end

  def edit
    @organization = Organization.find(params[:id])
    @events = @organization.events

    @new_event = @organization.events.build
    authorize @organization
  end
  
  def update
    @organization = Organization.find(params[:id])
    authorize @organization, :update?

    if @organization.update(organization_params)
      redirect_to @organization, notice: "L'association a été mise à jour avec succès."
    else
      render :edit
    end
  end

  ######### POUR GESTION DES EVENTS ##########

  def create_event
    @organization = Organization.find(params[:id])
    @event = @organization.events.build(event_params)
    authorize @event, :create?
    if @event.save
      redirect_to @organization, notice: "Événement créé avec succès."
    else
      render :edit
    end
  end

  def update_event
    @organization = Organization.find(params[:id])
    @event = Event.find(params[:event_id]) # Remarquez que nous récupérons l'event_id depuis les paramètres

    authorize @event, :update? # Assurez-vous d'autoriser l'utilisateur à effectuer cette action

    if @event.update(event_params)
      redirect_to @organization, notice: "Événement mis à jour avec succès."
    else
      render :edit
    end
  end

  ####################################################

  private

  def event_params
    params.require(:event).permit(:title, :description, :address, :start_time, :end_time, :picture)
  end

  def organization_params
    params.require(:organization).permit(:name, :address, :phone, :description, :avatar)
  end
end

app/views/organizations/_info_window.html.erb
<h5><%= event.title %></h5>
<p><%= event.address %></p>

app/views/organizations/edit.html.erb
<div class="container">
    <div class='prev-wrap pt-3'>
        <%= link_to :back, class: "btn-test" do %>
            <i class="fa fa-angle-left"></i> Précédent
        <% end %>
    </div>
    <section class="section-profil px-2">
        <div class="profil-page">
            <% if @organization.avatar.freeze %>
                <%= image_tag url_for(@organization.avatar), alt: "Avatar de #{@organization.name}", class: "profil-avatar" %>
            <% else %>
            <%= image_tag "cover.png", width: 100, height: 100, alt: "Avatar par défaut", class: "profil-avatar" %>
            <% end %>
        </div>
        <div class="case-profil ps-5">
            <div class="px-2 pt-1">
                <h5>Modifier les informations de votre association.</h5>
            </div>
        </div>
        <div class="container">
            <%= form_for @organization, url: organization_path(@organization), method: :patch, html: { multipart: true } do |f| %>
                <div class="form-group">
                    <%= f.label :description %>
                    <%= f.text_area :description, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :address, "Adresse"%>
                    <%= f.text_field :address, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :avatar, "Photo de l'association" %>
                    <%= f.file_field :avatar, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.submit "Enregistrer", class: "btn bouton-ac" %>
                </div>
            <% end %>
        </div>
    </section>
    <br>
    <section class="section-profil">
        <div class="container">
            <% if @events.any? { |event| event.id.present? } %>
                <h2>Événements de l'association</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Titre</th>
                            <th>Article</th>
                            <th>Date de début</th>
                            <th>Date de fin</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @events.each do |event| %>
                            <% if event.id.present? %>
                                <tr>
                                <td><%= event.title.truncate(20, omission: '..') %></td>
                                <td><%= event.articles.count %></th>
                                <td><%= event.start_time&.strftime('%d.%m à %H:%M') %></td>
                                <td><%= event.end_time&.strftime('%d.%m à %H:%M') %></td>
                                <td>
                                    <%= link_to edit_organization_event_path(@organization, event), class: 'btn btn-primary btn-sm' do %>
                                        <i class="fa-solid fa-circle-info"></i>
                                    <% end %>
                                    <%= link_to new_organization_event_article_path(@organization, event), class: 'btn btn-primary' do %>
                                        <i class="fa-regular fa-newspaper"></i>
                                    <% end %>
                                    <%= link_to organization_event_path(@organization, event), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Vous êtes sûr?"}, class: 'btn btn-danger' do %>
                                        <i class="fa-regular fa-circle-xmark"></i>
                                    <% end %>
                                </td>
                                </tr>
                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            <% else %>
                <p>Aucun événement trouvé pour cette association.</p>
            <% end %>
        </div>
        <div class="">
            <h2>Créer un nouvel évènement</h2>
            <%= form_for(@new_event, url: create_event_organization_path(@organization), method: :post, html: { multipart: true }) do |f| %>
                <div class="form-group">
                    <%= f.label :title, "Titre de l'événement" %>
                    <%= f.text_field :title, required: true, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :picture, "Photo de l'évènement" %>
                    <%= f.file_field :picture, required: true, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :description, "Description" %>
                    <%= f.text_area :description, required: true, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :address, "Adresse" %>
                    <%= f.text_field :address, required: true, class: "form-control" %>
                </div> 
                <div class="form-group">
                    <%= f.label :start_time, "Date et heure de début" %>
                    <%= f.datetime_local_field :start_time, required: true, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :end_time, "Date et heure de fin" %>
                    <%= f.datetime_local_field :end_time, required: true, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.submit "Créer l'événement", class: "btn bouton-ac" %>
                </div>
            <% end %>
        </div>
    </section>
</div>

app/views/organizations/index.html.erb
<% content_for :meta_title, "Liste des associations • Posilink" %>
<% content_for :meta_description, "Rejoigniez nos associations partenaires" %>

<div class="justify-content-center">
  <div class="container d-flex justify-content-center">
    <div class="col-sm-8 my-5">
      <%= form_with url: organizations_path, method: :get, class: "d-flex barre-recherche shadow-lg rounded-pill mb-4" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control recherche-input",
          placeholder: "Association"
        %>
        <%= submit_tag "Recherche", name: "", class: "nav-link py-1 px-2" %>
      <% end %>
    </div>
  </div>
  <!-- SCROLL X START -->
  <!-- <div class="container">
    <div class="row">
      <div class="col">
        <div class="event-card-grid pt-5">
          <% all_events = @organizations.map(&:events).flatten %>
            <% all_events.each_with_index do |event, index| %>
              <% rotation_degrees = index.even? ? 10 : -10 %>
              < class="event-card" style="transform: rotate(<%= rotation_degrees %>deg);">
                <h2><%= event.organization.name %></h2>

                <h2><%= event.title %></h2>
                <p><%= event.start_time.strftime("%d-%m-%Y") %></p>
                <%= link_to event.title, organization_event_path(event.organization, event), class: "button" %>
              </div>
            <% end %>
        </div>
      </div>
      
    </div>
  </div> -->
  <!-- SCROLL X END -->
  <% if current_user.director? %>
    <%= link_to edit_organization_path(@organization), class:"button" do %>
      Voir mon association
    <% end %>
  <% end %>
  <div class='bp-index-container mt-2'>
    <h1 class="titre-bold pb-2">TOUS NOS <span class="phrase-couleur">PARTENAIRES</span> <br>ASSOCIATIFS </h1>
    <div class="container">
      <div class='prev-wrap pt-3'>
        <%= link_to :back do %>
          <div class="btn-test"><i class="fa fa-angle-left"></i> Précédent </div>
        <% end %>
      </div>
      <div class="row align-items-center">
          <% @organizations.each do |organization| %>
            <div class="col-xl-4 col-md-6 pb-4">
              <div class="card card-ac">
                <div class="photo-taille-ac">
                  <% if organization.avatar.present? %>
                    <img src="<%= rails_blob_path(organization.avatar, disposition: "attachment") %>" alt="association <%= organization.name %>" class="object-fit-cover img-fluid">
                  <% end %>
                </div>
                <div class="card-body">
                  <h3 class="card-title titre-carte"><%= organization.name.upcase %></h3>
                </div>
                  <p class="card-text para-card"><%= organization.category %></p>
                <div class="card-bottom">
                  <a class="bouton-ac" onclick="window.location.href='<%= organization_path(organization) %>'">Voir <%= organization.name %> <i class="fa fa-arrow-right"></i></a>
                </div>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/organizations/show.html.erb
<% content_for :meta_title, "#{@organization.name} • Posilink" %>
<% content_for :meta_description, "Les derniers évènements de #{@organization.name}" %>
<% content_for :meta_image, rails_blob_path(@organization.avatar, disposition: "attachment") %>


<div class="organization-banner">
  <section class="dark">
    <div class="container py-4">
      <article class="postcard dark blue ">
        <div class="postcard__img_link" href="#">
          <img class="postcard__img" src="<%= rails_blob_path(@organization.avatar, disposition: "attachment") %>" alt="Image <%= @organization.name %>" />
        </div>
        <div class="postcard__text">
          <h1 class="postcard__title blue"> <%= @organization.name %></h1>
          <div class="postcard__subtitle small"></div>
          <div class="postcard__bar"></div>
          <div class=""> <%= @organization.description %></div>
          <ul class="postcard__tagbox">
            <li class="tag__item"><i class="fas fa-tag mr-2"></i><%= @organization.address %></li>
            <li class="tag__item"><a href="tel:<%= @organization.phone %>"><i class="fas fa-phone mr-2"></i><%= @organization.phone %></a></li>
            <li class="tag__item"><a href="mailto:<%= @organization.email %>"> <i class="fas fa-envelope mr-2"></i><%= @organization.email %></a></li>
          </ul>
        </div>
      </article>
    </div>
  </section>
  <div class="container">
    <div class="btn-wrap">
      <div class='btn-left'>
        <div class='prev-wrap'>
          <%= link_to :back, class: "btn-test" do %>
            <i class="fa fa-angle-left"></i> Précédent
          <% end %>
        </div>
          <% if @organization.directors.present? && current_user == @organization.directors.first.user %>
            <%= link_to edit_organization_path(@organization), class: "bouton-ac" do %>
              Modifier mon association
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
  <h2 class="mb-5"> Nos <span class="phrase-couleur">événements</span></h2>
  <div class="container-orga">
    <div class="cards-orga">
      <% @events.each do |event| %>
                <div class="card card-ac">
                  <% if event.picture.attached? %>
                    <img src="<%= rails_blob_path event.picture %>" alt="Événement" class="object-fit-cover img-fluid">
                  <% end %>
                  <div class="card-body">
                      <p class="date-start">Le <%= event.start_time.strftime('%d %m %Y') %><br>de <%= event.start_time.strftime('%H:%M')%> à <%= event.end_time.strftime('%H:%M')%><p>
                      <h3 class="card-title titre-carte"><%= event.title %></h3>   
                  </div>
                  <p class="para-card">Adresse</p>
                  <p class="para-card"><%= event.address %></p>
                  <div class="card-bottom">
                    <a class="bouton-ac" onclick="window.location.href='<%= event_path(event) %>'">Voir plus <i class="fa fa-arrow-right"></i></a>
                  </div>
                </div>
      <% end %>
    </div>
    <div id="map-event"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>